"""Add waveform_data and pitch_data fields

Revision ID: 54168fcb4787
Revises: 
Create Date: 2024-10-05 16:05:18.526535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54168fcb4787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waveform_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pitch_data', sa.Text(), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('recording_path',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('waveform_plot_path',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('pitch_plot_path',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_metadata', schema=None) as batch_op:
        batch_op.alter_column('pitch_plot_path',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('waveform_plot_path',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('recording_path',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('pitch_data')
        batch_op.drop_column('waveform_data')

    # ### end Alembic commands ###
